version: '3.7'

services:
  postgres-veraciousCaller:
    image: postgres
    ports:
      - "5432:5432"
    environment:
        POSTGRES_PASSWORD: admin
        POSTGRES_USER: admin
        POSTGRES_DB: boot 